---
- name: Download the plugin
  get_url:
    url: "https://artifacts.elastic.co/downloads/beats/{{ item }}/{{ item }}-{{ ELK_stack.major_version }}.\
         {{ ELK_stack.minor_version }}.{{ ELK_stack.patch }}-linux-x86_64.tar.gz"
    dest: "{{ ELK_stack.temp_folder}}"
  with_tems:
    - "{{ plugins }}"

- name: Install package.
  yum:
     name: "{{ ELK_stack.temp_folder}}/{{ item }}-{{ ELK_stack.major_version }}.{{ ELK_stack.minor_version }}.{{ ELK_stack.patch }}-x86_64.rpm"
     state: present
  with_tems:
    - "{{ plugins }}"

- name: Copy template for plugin
  template:
    src: "{{ item }}.j2"
    dest: "/etc/{{ item }}/{{ item }}.yml"
  with_tems:
    - "{{ plugins }}"

- name: Start service , if not started
  service:
    name: "{{ item }}"
    state: started
  with_tems:
    - "{{ plugins }}"