---
- name: Download the plugin
  get_url:
    url: "https://artifacts.elastic.co/downloads/beats/{{ item }}/{{ item }}-{{ ELK_stack.global.major_version }}.\
         {{ ELK_stack.global.minor_version }}.{{ ELK_stack.global.patch }}-x86_64.rpm"
    dest: "{{ ELK_stack.global.temp_folder}}"
  with_items:
    - "{{ ELK_stack.inputs.plugins }}"

- name: Install package.
  yum:
     name: "{{ ELK_stack.global.temp_folder}}/{{ item }}-{{ ELK_stack.global.major_version }}.\
            {{ ELK_stack.global.minor_version }}.{{ ELK_stack.global.patch }}-x86_64.rpm"
     state: present
  with_items:
    - "{{ ELK_stack.inputs.plugins }}"

- name: Copy template for plugin
  template:
    src: "{{ item }}.yml.j2"
    dest: "/etc/{{ item }}/{{ item }}.yml"
  with_items:
    - "{{ ELK_stack.inputs.plugins }}"

- name: Start service , if not started
  service:
    name: "{{ item }}"
    state: started
  with_items:
    - "{{ ELK_stack.inputs.plugins }}"

#filebeat setup --template -E output.logstash.enabled=false -E 'output.elasticsearch.hosts=["{{ groups['elastic_instances'][0] }}:9200"]'
#filebeat setup --dashboards