---
#- set_fact:
#    domains: "{{ ec2.instances | map(attribute='public_ip') | list | join(',') }}"

- name: Download the {{ ELK_stack.major_version }}.{{ ELK_stack.minor_version }}.{{ ELK_stack.patch }} version of plugin {{ item }}
  get_url:
    url: "https://artifacts.elastic.co/downloads/{{ item }}/{{ item }}-{{ ELK_stack.major_version }}.\
         {{ ELK_stack.minor_version }}.{{ ELK_stack.patch }}-linux-x86_64.tar.gz"
    dest: "{{ ELK_stack.temp_folder}}"
#  with_items:
#    - "{{plugins}}"

- name: Extract {{ item }} into {{ ELK_stack.temp_folder }}
  unarchive:
    src: "{{ ELK_stack.temp_folder}}/{{ item }}-{{ ELK_stack.major_version }}.{{ ELK_stack.minor_version }}.{{ ELK_stack.patch }}-linux-x86_64.tar.gz"
    dest: "{{ ELK_stack.temp_folder}}"
#  with_items:
#    - "{{plugins}}"

- name: Install package.
  yum:
     name: "{{ item }}-{{ ELK_stack.major_version }}.{{ ELK_stack.minor_version }}.{{ ELK_stack.patch }}-x86_64.rpm"
     state: present
#  with_items:
#    - "{{plugins}}"

- name: Copy template for plugin {{ item }}
  template:
    src: "{{ item }}.j2"
    dest: "/etc/{{ item }}/{{ item }}.yml"
#  vars:
#    ip_adresses: "{{ domains }}"
#  with_items:
#    - "{{plugins}}"

- name: Start service httpd, if not started
  service:
    name: "{{ item }}"
    state: started
#  with_items:
#    - "{{plugins}}"