---
- name: Download logstash
  get_url:
    url: "https://artifacts.elastic.co/downloads/logstash/logstash-{{ ELK_stack.global.major_version }}.\
         {{ ELK_stack.global.minor_version }}.{{ ELK_stack.global.patch }}.rpm"
    dest: "{{ ELK_stack.global.temp_folder}}"

- name: Install jdk.
  yum:
     name: "{{ ELK_stack.global.java_version }}"
     state: present

- name: Install logstash rpm.
  yum:
     name: "{{ ELK_stack.global.temp_folder}}/logstash-{{ ELK_stack.global.major_version }}.\
            {{ ELK_stack.global.minor_version }}.{{ ELK_stack.global.patch }}.rpm"
     state: present

- name: Copy main conf for logstash
  template:
    src: "logstash.conf.j2"
    dest: "/etc/logstash/conf.d/logstash.conf"

- name: Copy main conf for logstash
  template:
    src: "logstash.yml.j2"
    dest: "/etc/logstash/logstash.yml"

- name: Copy main log conf for logstash
  copy:
    src: "{{ item }}"
    dest: "/etc/logstash/{{ item }}"
    mode: 0755
  with_items:
    - "log4j2.properties"
    - "jvm.options"

- name: Execute the script
  shell: /usr/share/logstash/bin/system-install

- name: Start elasticsearch service, if not started
  service:
    name: logstash
    state: started

- pause: minutes=1