---
- name: VM_bootstrap
  hosts: localhost
  roles:
    - VM_bootstrap
  become_user: root
  become: True
  connection: local
  gather_facts: False

- name: show the groups the host(s) are in
  hosts: all
  gather_facts: no
  tasks:
  - name: show the groups the host(s) are in
    debug:
      msg: "{{group_names}}"

- name: Create tmp folder
  hosts: all
  gather_facts: no
  become_user: root
  tasks:
  - name: Create tmp folder
    file:
      path: "{{ ELK_stack.global.temp_folder}}"
      state: directory
      mode: 0755

- name: ELK install
  hosts: elastic_instances
  serial: 2
  roles:
    - elastik_install
  become_user: root
  become: True

- name: logstash_installation
  hosts: logstash
  roles:
    - logstash_install
  become_user: root
  become: True

- name: kibana_installation
  hosts: kibana
  roles:
    - kibana_install
  become_user: root
  become: True

- name: linux_server install
  hosts: linux_server
  roles:
    - install_senders
  become_user: root
  become: True
