---
- name: VM_bootstrap
  hosts: localhost
  roles:
    - VM_bootstrap
  become_user: root
  become: True
  connection: local
  gather_facts: False

- name: show the groups the host(s) are in
  hosts: all
  gather_facts: no
  tasks:
  - name: show the groups the host(s) are in
    debug:
      msg: "{{group_names}}"

- name: Create tmp folder
  hosts: all
  gather_facts: no
  become_user: root
#  vars:
#    ansible_user: ec2-user
#    ansible_ssh_private_key_file: /home/centos/mykey.pem
  tasks:
  - name: Create tmp folder
    file:
      path: "{{ ELK_stack.temp_folder}}"
      state: directory
      mode: 0755

#- name: linux_server install
#  hosts: linux_server
#  roles:
#    - install_senders
#  become_user: root
#  become: True
#  with_items:
#    - "{{ plugins }}"

- name: linux_server install
  hosts: linux_server
  become_user: root
  become: True
#  vars:
#    ansible_user: "{{ ansible_user }}"
#    ansible_ssh_private_key_file: "{{ ansible_ssh_private_key_file }}"
  roles :
    - role: install_senders
      with_items:
      - "{{ plugins }}"


#
#- name: ELK install
#  hosts: monitoring_*
#  serial: 2
#  roles:
#    - elastik_install
#    - kibana_install
#    - logstash_install
#  become_user: root
#  become: True
#
# - name: monitoring_1 install
#   hosts: monitoring_1
#   roles:
#     - prod_elastik_install
#   become_user: root
#   become: True
