---
ec2_vars:
  key_name: mykey
  instance_type: t2.micro
  image: ami-00284b413e05d88aa
  vpc_subnet_id: subnet-39ab9a62
  region: us-west-1
  group_id: sg-00a697b9100917dac
ELK_stack:
  hardware:
    linux_nodes: 1
    elastic_nodes: 2
    logstash_nodes: 1
    kibana_nodes: 1
    total_nodes: "{{ ELK_stack.hardware.linux_nodes + ELK_stack.hardware.elastic_nodes + ELK_stack.hardware.logstash_nodes + ELK_stack.hardware.kibana_nodes }}"
  global:
    major_version: 6
    minor_version: 5
    patch: 4
    temp_folder: /tmp/ELK
    cluster_name: test_cluster
    java_version: java-1.8.0-openjdk.x86_64
  kibana:
    kibana_port: 5601
  logstash:
    path_data: /var/lib/logstash
    path_logs: /var/log/logstash
    logstash_port: 5044
  inputs:
    plugins:
      - filebeat
  elasticsearch:
    path_data: /var/lib/elasticsearch
    path_logs: /var/log/elasticsearch
    elk_elasticsearch_pam_limits:
      - domain: elasticsearch
        limit_item: memlock
        limit_type: hard
        value: unlimited
      - domain: elasticsearch
        limit_item: memlock
        limit_type: soft
        value: unlimited
      - domain: elasticsearch
        limit_item: nofile
        limit_type: soft
        value: 65535
      - domain: elasticsearch
        limit_item: nofile
        limit_type: hard
        value: 65535
ansible_user: ec2-user
ansible_ssh_private_key_file: /home/centos/mykey.pem
# Support multiple plugins enabled, just for test - only filebeat

