---
production: false
production_nodes: 5
non_production_nodes: 3
ec2_vars:
  key_name: mykey
  instance_type: t2.micro
  image: ami-00284b413e05d88aa
  vpc_subnet_id: subnet-39ab9a62
  region: us-west-1
  group_id: sg-00a697b9100917dac
ELK_stack:
  major_version: 6
  minor_version: 5
  patch: 4
  temp_folder: /tmp/ELK
plugins:
  - filebeat
ansible_user: ec2-user
ansible_ssh_private_key_file: /home/centos/mykey.pem
# Support multiple plugins enabled, just for test - only filebeat

