---
- name: Download kibana
  get_url:
    url: "https://artifacts.elastic.co/downloads/kibana/kibana-{{ ELK_stack.global.major_version }}.\
         {{ ELK_stack.global.minor_version }}.{{ ELK_stack.global.patch }}-x86_64.rpm"
    dest: "{{ ELK_stack.global.temp_folder}}"

- name: Install kibana rpm.
  yum:
     name: "{{ ELK_stack.global.temp_folder}}/kibana-{{ ELK_stack.global.major_version }}.\
            {{ ELK_stack.global.minor_version }}.{{ ELK_stack.global.patch }}-x86_64.rpm"
     state: present

- name: Copy template for plugin
  template:
    src: "kibana.yml.j2"
    dest: "/etc/kibana/kibana.yml"

- name: Start kibana service, if not started
  service:
    name: kibana
    state: started

- pause: minutes=1

- name: Check kibana web-UI
  uri:
    url: "http://{{ inventory_hostname }}:{{ ELK_stack.kibana.kibana_port }}"
    status_code: ['200','503']
  retries: 6
  delay: 10

- name: check parameter
  debug:
    msg: "{{ inventory_hostname }}"